# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Run linter and verify docker image

on:
  pull_request:

jobs:
  pylama:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python and poetry dependencies
        uses: ./.github/workflows/python-and-poetry

      - name: Run pylama
        run: poetry run pylama
  pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python and poetry dependencies
        uses: ./.github/workflows/python-and-poetry

      - name: Run pytests
        working-directory: tests
        run: poetry run pytest
  verify-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
